### ISSUE TITLE
Openvas Plugin issue

### ISSUE THREAD

**Issue by rakesh-dhn** [golismero/golismero#24]
I am trying to run the Golismero with Openvas plugin. Its gving the below error although all the parameters for the openvas is correctly modified. Please check into the below issue and help out with a solution.

The openvas conf is :
  [openvas]
  host = xxxxxxxxxxx
  port = xxxxxx
  user = admin
 *password = admin       

golismero scan xxxxxxxxxxx -e openvas

[!] OpenVAS: Plugin disabled, reason: Missing status property in response
[!] OpenVAS: Traceback (most recent call last):
  File "/opt/golismero/golismero/managers/pluginmanager.py", line 1535, in __check_plugin_params
    plugin.check_params()
  File "/opt/golismero/plugins/testing/scan/openvas.py", line 151, in check_params
    VulnscanManager(m_host, m_user, m_password, m_port, m_timeout)
  File "/opt/golismero/thirdparty_libs/openvas_lib/__init__.py", line 490, in __init__
    self.__manager = get_connector(host, user, password, port, m_time_out)
  File "/opt/golismero/thirdparty_libs/openvas_lib/common.py", line 69, in get_connector
    manager = ConnectionManager(host, username, password, port, timeout)
  File "/opt/golismero/thirdparty_libs/openvas_lib/common.py", line 144, in __init__
    self._connect()
  File "/opt/golismero/thirdparty_libs/openvas_lib/common.py", line 183, in _connect
    self._authenticate(self.__username, self.__password)
  File "/opt/golismero/thirdparty_libs/openvas_lib/common.py", line 211, in _authenticate
    self.make_xml_request(m_request)
  File "/opt/golismero/thirdparty_libs/openvas_lib/common.py", line 360, in make_xml_request
    raise ValueError('Missing status property in response')
ValueError: Missing status property in response

**Comment by XTpeeps** [comment]
i have the same question.  @MarioVilas

**Comment by XTpeeps** [comment]
[!] OpenVAS: Plugin disabled, reason: Missing status property in response
[!] OpenVAS: Traceback (most recent call last):
  File "D:\HackProgram\golismero-master\golismero\managers\pluginmanager.py", line 1535, in __check_plugin_params
    plugin.check_params()
  File "D:\HackProgram\golismero-master\plugins\testing\scan\openvas.py", line 151, in check_params
    VulnscanManager(m_host, m_user, m_password, m_port, m_timeout)
  File "D:\HackProgram\golismero-master\thirdparty_libs\openvas_lib\__init__.py", line 496, in __init__
    self.__manager = get_connector(host, user, password, port, m_time_out, ssl_verify)
  File "D:\HackProgram\golismero-master\thirdparty_libs\openvas_lib\common.py", line 73, in get_connector
    manager = ConnectionManager(host, username, password, port, timeout, ssl_verify)
  File "D:\HackProgram\golismero-master\thirdparty_libs\openvas_lib\common.py", line 149, in __init__
    self._connect()
  File "D:\HackProgram\golismero-master\thirdparty_libs\openvas_lib\common.py", line 200, in _connect
    self._authenticate(self.__username, self.__password)
  File "D:\HackProgram\golismero-master\thirdparty_libs\openvas_lib\common.py", line 229, in _authenticate
    self.make_xml_request(m_request)
  File "D:\HackProgram\golismero-master\thirdparty_libs\openvas_lib\common.py", line 379, in make_xml_request
    raise ValueError('Missing status property in response')
ValueError: Missing status property in response
